load_state: 0
dir: /raid/javier/Projects/PhaseClassifier/Results

run_path: ""
config_path: /home/javier/Projects/PhaseClassifier/output_sym/wandb/run-20250823_130802-6welshyl/files/transformer_Final_config.yaml

device: gpu
gpu_list:
  - 2

defaults:
  - data: Ising
  - wandb: dgx
  - model: model1
  - engine: engine1
  - _self_

n_epochs: 25
epoch_start: 0